py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2020-2021\Semester 1" > detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2020-2021\Semester 1B" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2020-2021\Semester 2" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2021-2022\Periode 1" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2021-2022\Periode 2" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2021-2022\Periode 3" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2021-2022\Periode 4" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2022-2023\Periode 1" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2022-2023\Periode 2" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2022-2023\Periode 3" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2022-2023\Periode 4" >> detect.out
py aapa.py -debug -preview --detect="C:\Users\david\NHL Stenden\HBO-ICT Afstuderen - Software Engineering\2023-2024" >> detect.out
